spring:
  config:
    import: optional:classpath:application-secret.yaml
  application:
    name: sichuation
  ai:
    google:
      genai:
        chat:
          options:
            model: gemini-2.5-flash

logging:
  level:
    org.springframework.ai: DEBUG
