spring:
  application:
    name: sichuation
  ai:
    google:
      genai:
        api-key: AIzaSyBOYAABy3Q4UMU8NMq674e7nDToMpKaFzU
        chat:
          options:
            model: gemini-2.5-flash

logging:
  level:
    org.springframework.ai: DEBUG
