spring:
  application:
    name: sichuation
  ai:
    google:
      genai:
        api-key: AIzaSyAh2ytC0imngFBTBr_a3JS2NE0dqRgz9es
        chat:
          options:
            model: gemini-2.5-flash

logging:
  level:
    org.springframework.ai: DEBUG
